### ISSUE TITLE
NoSuchMethodError on load

### ISSUE THREAD

**Issue by funniray** [CloudburstMC/SynapseAPI#1]
#I'm running the latest version of NukkitX and I'm getting this error when the plugin try's to connect to my Nemisys server. I'm using the latest version of NukkitX, Nemisys and Nemisys.
```
java.lang.NoSuchMethodError: cn.nukkit.utils.BinaryStream.reset()V
        at org.itxtech.synapseapi.network.protocol.spp.SynapseDataPacket.reset(SynapseDataPacket.java:18)
        at org.itxtech.synapseapi.network.protocol.spp.ConnectPacket.encode(ConnectPacket.java:22)
        at org.itxtech.synapseapi.network.SynapseInterface.putPacket(SynapseInterface.java:62)
        at org.itxtech.synapseapi.SynapseEntry.sendDataPacket(SynapseEntry.java:129)
        at org.itxtech.synapseapi.SynapseEntry.connect(SynapseEntry.java:189)
        at org.itxtech.synapseapi.network.SynapseInterface.process(SynapseInterface.java:81)
        at org.itxtech.synapseapi.SynapseEntry.threadTick(SynapseEntry.java:261)
        at org.itxtech.synapseapi.SynapseEntry$AsyncTicker.run(SynapseEntry.java:199)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by Creeperface01** [comment]
Fixed in #2
