### ISSUE TITLE
Incompatible with the # 466 NukkitX core

### ISSUE THREAD

**Issue by junxiesky** [CloudburstMC/SynapseAPI#15]
13:19:10 [WARN ] 发现损坏的玩家数据 "f1e2c0e9-3394-33e4-a95b-447f3988bf06"，正在创建新的数据
13:19:10 [ERROR] Throwing
java.io.EOFException: null
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268) ~[?:1.8.0_222]
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258) ~[?:1.8.0_222]
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164) ~[?:1.8.0_222]
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79) ~[?:1.8.0_222]
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91) ~[?:1.8.0_222]
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:112) ~[nukkit.jar:?]
        at cn.nukkit.nbt.NBTIO.readCompressed(NBTIO.java:108) ~[nukkit.jar:?]
        at cn.nukkit.Server.getOfflinePlayerDataInternal(Server.java:1602) [nukkit.jar:?]
        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1576) [nukkit.jar:?]
        at cn.nukkit.Server.getOfflinePlayerData(Server.java:1572) [nukkit.jar:?]
        at org.itxtech.synapseapi.SynapsePlayer.processLogin(SynapsePlayer.java:149) [synapse-api.jar:?]
        at cn.nukkit.Player.handleDataPacket(Player.java:2202) [nukkit.jar:?]
        at org.itxtech.synapseapi.SynapsePlayer.handleDataPacket(SynapsePlayer.java:431) [synapse-api.jar:?]
        at org.itxtech.synapseapi.SynapsePlayer.handleLoginPacket(SynapsePlayer.java:92) [synapse-api.jar:?]
        at org.itxtech.synapseapi.SynapseEntry$Ticker.run(SynapseEntry.java:254) [synapse-api.jar:?]
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99) [nukkit.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.runTasks(ServerScheduler.java:296) [nukkit.jar:?]
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:277) [nukkit.jar:?]
        at cn.nukkit.Server.tick(Server.java:1132) [nukkit.jar:?]
        at cn.nukkit.Server.tickProcessor(Server.java:903) [nukkit.jar:?]
        at cn.nukkit.Server.start(Server.java:880) [nukkit.jar:?]
        at cn.nukkit.Server.<init>(Server.java:565) [nukkit.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit.jar:?]
13:19:10 [INFO ] CN206611[/139.215.13.39:18926] 登出游戏，原因：Invalid data

**Comment by SupremeMortal** [comment]
Please use the latest build. 2d8cb8a0a90845fc758ad8ac15498d4660871894
